services:
  db:
    image: postgres
    restart: always
    volumes:
       - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: vcbot
      POSTGRES_PASSWORD: password

  bot:
    build: .
    restart: on-failure